var programsData = [
  {
    full: false,
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Испания',
    webp: 'img/program-1.webp',
    jpg: 'img/program-1.jpg',
    alt: 'Malaga Summer camp',
    name: 'Malaga Summer camp',
    location: 'Испания, Малага',
    date: '<a href="http://summer.study.ua/trip/look/1090" target="_blank">30.06 - 13.07 (2 нед.)</a>',
    cost: '€2700 (3 нед.)'
  },
  {
    full: false,
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Испания',
    webp: 'img/program-2.webp',
    jpg: 'img/program-2.jpg',
    alt: 'Barcelona Summer camp',
    name: 'Barcelona Summer camp',
    location: 'Барселона',
    date: '<a href="http://summer.study.ua/trip/look/1097" target="_blank">14.07 - 27.07 (2 нед.)</a><br><a href="http://summer.study.ua/trip/look/1096" target="_blank">28.07 - 10.08 (2 нед.)</a>',
    cost: '€2800 (2 нед.)'
  },
  {
    full: false,
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Испания',
    webp: 'img/program-3.webp',
    jpg: 'img/program-3.jpg',
    alt: 'EU International Business school',
    name: 'EU International Business school',
    location: 'Барселона',
    date: '<a>07.07 - 20.07 (2 нед.)</a><br><a>04.08 - 17.08 (2 нед.)</a><br><a href="http://summer.study.ua/trip/look/1103" target="_blank">07.07 - 27.07 (3 нед.)</a><br><a href="http://summer.study.ua/trip/look/1101" target="_blank">04.08 - 24.08 (3 нед.)</a>',
    cost: '€3200 (2 нед.)<br>€4200 (3 нед.)'
  },
  {
    full: false,
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-4.webp',
    jpg: 'img/program-4.jpg',
    alt: 'Alpadia Summer camp',
    name: 'Alpadia Summer camp',
    location: 'Энгельберг',
    date: '<a href="http://summer.study.ua/trip/look/57" target="_blank">30.06 - 13.07 (2 нед.)</a><br><a href="http://summer.study.ua/trip/look/1094" target="_blank">14.07 - 27.07 (2 нед.)</a>',
    cost: '$3800 (2 нед.)'
  },
  {
    full: false,
    flagWebp: 'img/programs-malta.webp',
    flag: 'img/programs-malta.jpg',
    flagAlt: 'Мальта',
    webp: 'img/program-5.webp',
    jpg: 'img/program-5.jpg',
    alt: 'Malta IELS',
    name: 'Malta IELS',
    location: 'Слима',
    date: '<a href="http://summer.study.ua/trip/look/1120" target="_blank">22.06 – 06.07 (2 нед.)</a><br><a href="http://summer.study.ua/trip/look/1121" target="_blank">10.08 - 24.08 (2 нед.)</a>',
    cost: '€2800 (2 нед.)'
  },
  {
    full: false,
    flagWebp: 'img/programs-germany.webp',
    flag: 'img/programs-germany.jpg',
    flagAlt: 'Германия',
    webp: 'img/program-6.webp',
    jpg: 'img/program-6.jpg',
    alt: 'GLS Munich Castle',
    name: 'GLS Munich Castle',
    location: 'Мюнхен',
    date: '<a href="http://summer.study.ua/trip/look/1122" target="_blank">14.07 - 28.07 (2 нед.)</a>',
    cost: '€3200 (2 нед.)'
  },
  {
    full: false,
    flagWebp: 'img/programs-france.webp',
    flag: 'img/programs-france.jpg',
    flagAlt: 'Франция',
    webp: 'img/program-7.webp',
    jpg: 'img/program-7.jpg',
    alt: 'French Riviera summer',
    name: 'French Riviera summer',
    location: 'Ницца',
    date: '<a href="http://summer.study.ua/trip/look/62" target="_blank">29.06 - 13.07 (2 нед.)</a><br><a href="http://summer.study.ua/trip/look/75" target="_blank">13.07 - 27.07 (2 нед.)</a><br><a href="http://summer.study.ua/trip/look/1077" target="_blank">27.07 - 10.08 (2 нед.)</a>',
    cost: '€2700 (2 нед.)'
  },
  {
    full: false,
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-8.webp',
    jpg: 'img/program-8.jpg',
    alt: 'Business and Hotel Management School',
    name: 'Business and Hotel Management School',
    location: 'Люцерн',
    date: '<a href="http://summer.study.ua/trip/look/61" target="_blank">06.07 - 19.07 (2 нед.)</a>',
    cost: '$4500 (2 нед.)'
  }
];