var programsData = [
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/university-of-toronto/',
    webp: 'img/program-1.webp',
    jpg: 'img/program-1.jpg',
    alt: 'University of Toronto',
    name: 'University of Toronto',
    location: 'Торонто',
    age: '12-17',
    date: '<a href="https://holidays.study.ua/trips/page/university-of-toronto/" target="_blank">18.07 - 08.08 (3 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/university-of-toronto/" target="_blank">25.07 - 15.08 (3 нед.)</a>',
    cost: '$5500 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/mcgill-university-university-of-toronto/',
    webp: 'img/program-2.webp',
    jpg: 'img/program-2.jpg',
    alt: 'University of Toronto + McGill University',
    name: 'University of Toronto + McGill University',
    location: 'Торонто + Монреаль',
    age: '12-17',
    date: '<a href="https://holidays.study.ua/trips/page/mcgill-university-university-of-toronto/" target="_blank">27.06 - 25.07 (3 нед.)</a>',
    cost: '$6500 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/braemar-college/',
    webp: 'img/program-3.webp',
    jpg: 'img/program-3.jpg',
    alt: 'Braemar College',
    name: 'Braemar College',
    location: 'Торонто',
    age: '13-18',
    date: '<a href="https://holidays.study.ua/trips/page/braemar-college/" target="_blank">01.07 - 19.08 (7 нед.)</a>',
    cost: '$7700 (7 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/sheridan-college/',
    webp: 'img/program-4.webp',
    jpg: 'img/program-4.jpg',
    alt: 'Sheridan College',
    name: 'Sheridan College',
    location: 'Оуквилль',
    age: '12-17',
    date: '<a href="https://holidays.study.ua/trips/page/sheridan-college/" target="_blank">01.07 - 15.07 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/sheridan-college/" target="_blank">15.07 - 29.07 (2 нед.)</a>',
    cost: '$4400 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/international-language-academy-of-canada/',
    webp: 'img/program-5.webp',
    jpg: 'img/program-5.jpg',
    alt: 'ILAC',
    name: 'ILAC',
    location: 'Торонто',
    age: '14-17',
    date: '<a href="https://holidays.study.ua/trips/page/international-language-academy-of-canada/" target="_blank">11.07 - 01.08 (3 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/international-language-academy-of-canada/" target="_blank">01.08 - 22.08 (3 нед.)</a>',
    cost: '$4650 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/university-of-british-columbia-/',
    webp: 'img/program-6.webp',
    jpg: 'img/program-6.jpg',
    alt: 'University of British Columbia',
    name: 'University of British Columbia',
    location: 'Ванкувер',
    age: '10-17',
    date: '<a href="https://holidays.study.ua/trips/page/university-of-british-columbia-/" target="_blank">12.07 - 02.08 (3 нед.)</a>',
    cost: '$5800 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/ilsc-toronto-academic-english/',
    webp: 'img/program-7.webp',
    jpg: 'img/program-7.jpg',
    alt: 'ILSC',
    name: 'ILSC',
    location: 'Торонто',
    age: '13-17',
    date: '<a href="https://holidays.study.ua/trips/page/ilsc-toronto-academic-english/" target="_blank">13.06 - 11.07 (4 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/ilsc-toronto-academic-english/" target="_blank">11.07 - 08.08 (4 нед.)</a>',
    cost: '$5250 (4 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/ubc-ryerson/',
    webp: 'img/program-8.webp',
    jpg: 'img/program-8.jpg',
    alt: 'UBC Vancouver + Ryerson University',
    name: 'UBC Vancouver + Ryerson University',
    location: 'Торонто',
    age: '12-17',
    date: '<a href="https://holidays.study.ua/trips/page/ubc-ryerson/" target="_blank">05.07 - 19.07 (3 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/ubc-ryerson/" target="_blank">19.07 - 26.07 (3 нед.)</a>',
    cost: '$6150 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/mohawk-college-students/',
    webp: 'img/program-9.webp',
    jpg: 'img/program-9.jpg',
    alt: 'Mohawk College',
    name: 'Mohawk College',
    location: 'Гамильтон',
    age: '10-17',
    date: '<a href="https://holidays.study.ua/trips/page/mohawk-college-students/" target="_blank">04.07 - 25.07 (3 нед.)</a>',
    cost: '$4400 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/ilsc-toronto/',
    webp: 'img/program-10.webp',
    jpg: 'img/program-10.jpg',
    alt: 'ILSC Chestnut',
    name: 'ILSC Chestnut',
    location: 'Торонто',
    age: '13-17',
    date: '<a href="https://holidays.study.ua/trips/page/ilsc-toronto/" target="_blank">18.07 - 08.08 (3 нед.)</a>',
    cost: '$5250 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/ilsc-toronto-vancouver/',
    webp: 'img/program-11.webp',
    jpg: 'img/program-11.jpg',
    alt: 'ILSC Toronto + Vancouver',
    name: 'ILSC Toronto + Vancouver',
    location: 'Торонто, Ванкувер',
    age: '13-17',
    date: '<a href="https://holidays.study.ua/trips/page/ilsc-toronto-vancouver/" target="_blank">18.07 - 08.08 (3 нед.)</a>',
    cost: '$5650 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/calgary-toronto-canada/',
    webp: 'img/program-12.webp',
    jpg: 'img/program-12.jpg',
    alt: 'Calgary + Toronto',
    name: 'Calgary + Toronto',
    location: 'Калгари, Торонто',
    age: '13-17',
    date: '<a href="https://holidays.study.ua/trips/page/calgary-toronto-canada/" target="_blank">28.06 - 26.07 (4 нед.)</a>',
    cost: '$5400 (4 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/niagara-college-students/',
    webp: 'img/program-13.webp',
    jpg: 'img/program-13.jpg',
    alt: 'Niagara College',
    name: 'Niagara College',
    location: 'Велланд',
    age: '16-23',
    date: '<a href="https://holidays.study.ua/trips/page/niagara-college-students/" target="_blank">25.07 - 22.08 (4 нед.)</a>',
    cost: '$4700 (4 нед.)'
  }
];