var programsData = [
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/38',
    webp: 'img/program-1.webp',
    jpg: 'img/program-1.jpg',
    alt: 'Royal Holloway, University of London',
    name: 'Royal Holloway, University of London',
    location: 'Лондон',
    age: '10-17',
    date: '<a href="http://summer.study.ua/trip/look/38" target="_blank">18.06 - 02.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/23" target="_blank">02.07 - 16.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1135" target="_blank">16.07 - 30.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/22" target="_blank">30.07 - 13.08 (2 нед.)</a>',
    cost: '$3600 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/58',
    webp: 'img/program-2.webp',
    jpg: 'img/program-2.jpg',
    alt: 'CATS College London Bloomsbury',
    name: 'CATS College London Bloomsbury',
    location: 'Лондон',
    age: '12-17',
    date: '<a href="http://summer.study.ua/trip/look/58" target="_blank">02.08 - 23.08 (3 нед.)</a>',
    cost: '$4800 (3 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/33',
    webp: 'img/program-3.webp',
    jpg: 'img/program-3.jpg',
    alt: 'Brunel University',
    name: 'Brunel University',
    location: 'Лондон',
    age: '10-17',
    date: '<a href="http://summer.study.ua/trip/look/33" target="_blank">21.06 - 05.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/29" target="_blank">05.07 - 26.07 (3 нед.)</a>',
    cost: '$3500 (2 нед.) <br> $4800 (3 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/35',
    webp: 'img/program-4.webp',
    jpg: 'img/program-4.jpg',
    alt: 'Royal Holloway, University of London + Tottenham Hotspur Football',
    name: 'Royal Holloway, University of London + Tottenham Hotspur Football',
    location: 'Лондон',
    age: '12-17',
    date: '<a href="http://summer.study.ua/trip/look/35" target="_blank">02.07 - 16.07 (2 нед.)</a>',
    cost: '$3980 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/1108',
    webp: 'img/program-5.webp',
    jpg: 'img/program-5.jpg',
    alt: 'Roedean School',
    name: 'Roedean School',
    location: 'Брайтон',
    age: '10-17',
    date: '<a href="http://summer.study.ua/trip/look/1108" target="_blank">28.06 - 11.07 (2 нед.)</a>',
    cost: '$3400 (2 нед.)'
  },
  // {
  //   full: false,
  //   href: 'http://summer.study.ua/trip/look/1104',
  //   webp: 'img/program-6.webp',
  //   jpg: 'img/program-6.jpg',
  //   alt: 'Brighton College',
  //   name: 'Brighton College',
  //   location: 'Брайтон',
  //   age: '12-17',
  //   date: '<a href="http://summer.study.ua/trip/look/1104" target="_blank">03.07 - 17.07 (2 нед.)</a>',
  //   cost: '$3450 (2 нед.)'
  // },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/1111',
    webp: 'img/program-7.webp',
    jpg: 'img/program-7.jpg',
    alt: 'Wellington College',
    name: 'Wellington College',
    location: 'Виндзор',
    age: '10-17',
    date: '<a href="http://summer.study.ua/trip/look/1111" target="_blank">01.07 - 15.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1112" target="_blank">15.07 - 29.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1113" target="_blank">29.07 - 12.08 (2 нед.)</a>',
    cost: '$3300 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/1082',
    webp: 'img/program-8.webp',
    jpg: 'img/program-8.jpg',
    alt: 'Queen Ethelburga’s College + Edinburgh trip',
    name: 'Queen Ethelburga’s College + Edinburgh trip',
    location: 'Йорк',
    age: '8-17',
    date: '<a href="http://summer.study.ua/trip/look/1082" target="_blank">28.06 - 12.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/34" target="_blank">05.07 - 19.07 (2 нед.)</a>',
    cost: '$3750 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/4',
    webp: 'img/program-9.webp',
    jpg: 'img/program-9.jpg',
    alt: 'Oxford School of English',
    name: 'Oxford School of English',
    location: 'Оксфорд',
    age: '12-17',
    date: '<a href="http://summer.study.ua/trip/look/4" target="_blank">05.07 - 26.07 (3 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/16" target="_blank">26.07 - 09.08 (2 нед.)</a>',
    cost: '$3600 (3 нед.) <br> $3000 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/65',
    webp: 'img/program-10.webp',
    jpg: 'img/program-10.jpg',
    alt: 'Abbey DLD Academic summer',
    name: 'Abbey DLD Academic summer',
    location: 'Лондон',
    age: '13-18',
    date: '<a href="http://summer.study.ua/trip/look/65" target="_blank">04.07 - 18.07 (2 нед.)</a>',
    cost: '$4700 (2 нед.)'
  },
  {
    full: false,
    href: '',
    webp: 'img/program-11.webp',
    jpg: 'img/program-11.jpg',
    alt: 'Abbey DLD Academic summer Medical School',
    name: 'Abbey DLD Academic summer Medical School',
    location: 'Лондон',
    age: '12-17',
    date: '<a target="_blank">04.07 - 18.07 (2 нед.)</a>',
    cost: '$5250 (2 нед.)'
  },
  {
    full: false,
    href: 'program/studio-cambridge.html',
    webp: 'img/program-12.webp',
    jpg: 'img/program-12.jpg',
    alt: 'Studio Cambridge',
    name: 'Studio Cambridge',
    location: 'Кембридж',
    age: '13-17',
    date: '<a href="program/studio-cambridge.html" target="_blank">09.08 - 23.08 (2 нед.)</a>',
    cost: '$3500 (2 нед.)'
  },
  {
    full: false,
    href: 'program/the-royal-high-school.html',
    webp: 'img/program-13.webp',
    jpg: 'img/program-13.jpg',
    alt: 'The Royal High School',
    name: 'The Royal High School',
    location: 'Бат',
    age: '10-17',
    date: '<a href="program/the-royal-high-school.html" target="_blank">08.07 - 22.07 (2 нед.)</a> <br> <a href="program/the-royal-high-school.html" target="_blank">22.07 - 05.08 (2 нед.)</a>',
    cost: '$3500 (2 нед.)'
  },
  {
    full: false,
    href: 'program/dover-college.html',
    webp: 'img/program-14.webp',
    jpg: 'img/program-14.jpg',
    alt: 'Dover College',
    name: 'Dover College',
    location: 'Дувр',
    age: '11-17',
    date: '<a href="program/dover-college.html" target="_blank">07.06 - 21.06 (2 нед.)</a> <br> <a href="program/dover-school.html" target="_blank">07.06 - 28.06 (3 нед.)</a>',
    cost: '$3700 (2 нед.) <br> $4800 (3 нед.)'
  },
  {
    full: false,
    href: 'program/kings-college-london.html',
    webp: 'img/program-15.webp',
    jpg: 'img/program-15.jpg',
    alt: "King's College London",
    name: "King's College London",
    location: 'Лондон',
    age: '12-17',
    date: '<a href="program/kings-college-london.html" target="_blank">15.08 - 29.08 (2 нед.)</a>',
    cost: '$3750 (2 нед.)'
  },
  {
    full: false,
    href: 'program/university-of-brighton.html',
    webp: 'img/program-16.webp',
    jpg: 'img/program-16.jpg',
    alt: "University of Brighton",
    name: "University of Brighton",
    location: 'Брайтон',
    age: '10-17',
    date: '<a href="program/university-of-brighton.html" target="_blank">15.07 - 29.07 (2 нед.)</a>',
    cost: '$3600 (2 нед.)'
  },
  {
    full: false,
    href: 'program/university-of-brighton-academic-course.html',
    webp: 'img/program-17.webp',
    jpg: 'img/program-17.jpg',
    alt: "University of Brighton Academic course",
    name: "University of Brighton Academic course",
    location: 'Брайтон',
    age: '10-17',
    date: '<a href="program/university-of-brighton-academic-course.html" target="_blank">15.07 - 29.07 (2 нед.)</a>',
    cost: '$3950 (2 нед.)'
  },
  {
    full: false,
    href: 'program/university-of-brighton-football-camp.html',
    webp: 'img/program-18.webp',
    jpg: 'img/program-18.jpg',
    alt: "University of Brighton Football Camp",
    name: "University of Brighton Football Camp",
    location: 'Брайтон',
    age: '12-17',
    date: '<a href="program/university-of-brighton-football-camp.html" target="_blank">15.07 - 29.07 (2 нед.)</a>',
    cost: '$3900 (2 нед.)'
  },
  {
    full: false,
    href: 'program/charterhouse-school.html',
    webp: 'img/program-19.webp',
    jpg: 'img/program-19.jpg',
    alt: "Charterhouse School Chelsea Camp",
    name: "Charterhouse School Chelsea Camp",
    location: 'Годалминг, Лондон',
    age: '13-17',
    date: '<a href="program/charterhouse-school.html" target="_blank">27.07 - 09.08 (2 нед.)</a>',
    cost: '$4800 (2 нед.)'
  },
  {
    full: false,
    href: 'program/university-of-stirling.html',
    webp: 'img/program-20.webp',
    jpg: 'img/program-20.jpg',
    alt: "University of Stirling",
    name: "University of Stirling",
    location: 'Стирлинг',
    age: '11-17',
    date: '<a href="program/university-of-stirling.html" target="_blank">01.07 - 15.07 (2 нед.)</a>',
    cost: '$3600 (2 нед.)'
  },
  {
    full: false,
    href: 'program/kings-college-london-edinburgh-academy.html',
    webp: 'img/program-21.webp',
    jpg: 'img/program-21.jpg',
    alt: "King's College London + Edinburgh Academy",
    name: "King's College London + Edinburgh Academy",
    location: 'Лондон, Англия <br> Эдинбург, Шотландия',
    age: '12-17',
    date: '<a href="program/kings-college-london-edinburgh-academy.html" target="_blank">05.07 - 26.07 (3 нед.)</a>',
    cost: '$4800 (2 нед.)'
  }
];