var programsData = [
  // {
  //   full: false,
  //   href: 'http://summer.study.ua/trip/look/1109',
  //   flagWebp: 'img/programs-spain.webp',
  //   flag: 'img/programs-spain.jpg',
  //   flagAlt: 'Испания',
  //   webp: 'img/program-1.webp',
  //   jpg: 'img/program-1.jpg',
  //   alt: 'Malaga Summer camp',
  //   name: 'Malaga Summer camp',
  //   location: 'Испания, Малага',
  //   age: '11-17',
  //   date: '<a href="http://summer.study.ua/trip/look/1109" target="_blank">05.07 - 18.07 (2 нед.)</a>',
  //   cost: '€2750 (2 нед.)'
  // },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/barcelona-summer-camp/',
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Испания',
    webp: 'img/program-2.webp',
    jpg: 'img/program-2.jpg',
    alt: 'Barcelona Summer camp',
    name: 'Barcelona Summer camp',
    location: 'Барселона, Испания',
    age: '14-18',
    date: '<a href="https://holidays.study.ua/trips/page/barcelona-summer-camp/" target="_blank">05.07 - 18.07 (2 нед.)</a>',
    cost: '€2800 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/eu-business-school/',
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Испания',
    webp: 'img/program-3.webp',
    jpg: 'img/program-3.jpg',
    alt: 'EU International Business school',
    name: 'EU International Business school',
    location: 'Барселона, Испания',
    age: '16-18',
    date: '<a href="https://holidays.study.ua/trips/page/eu-business-school/" target="_blank">05.07 - 25.07 (3 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/eu-business-school/" target="_blank">02.08 - 22.08 (3 нед.)</a>',
    cost: '€4600 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/alpadia-swiss-summer-camp/',
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-4.webp',
    jpg: 'img/program-4.jpg',
    alt: 'Alpadia Summer camp',
    name: 'Alpadia Summer camp',
    location: 'Энгельберг, Швейцария',
    age: '10-17',
    date: '<a href="https://holidays.study.ua/trips/page/alpadia-swiss-summer-camp/" target="_blank">28.06 - 11.07 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/alpadia-swiss-summer-camp/" target="_blank">11.07 - 25.07 (2 нед.)</a>',
    cost: '$3800 (2 нед.)'
  },
  // {
  //   full: false,
  //   href: 'http://summer.study.ua/trip/look/1120',
  //   flagWebp: 'img/programs-malta.webp',
  //   flag: 'img/programs-malta.jpg',
  //   flagAlt: 'Мальта',
  //   webp: 'img/program-5.webp',
  //   jpg: 'img/program-5.jpg',
  //   alt: 'Malta IELS',
  //   name: 'Malta IELS',
  //   location: 'Слима',
  //   age: '13-17',
  //   date: '<a href="http://summer.study.ua/trip/look/1120" target="_blank">05.07 - 19.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1121" target="_blank">26.07 - 09.08 (2 нед.)</a>',
  //   cost: '$2550 (2 нед.)'
  // },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/gls-munich-castle/',
    flagWebp: 'img/programs-germany.webp',
    flag: 'img/programs-germany.jpg',
    flagAlt: 'Германия',
    webp: 'img/program-6.webp',
    jpg: 'img/program-6.jpg',
    alt: 'GLS Munich Castle',
    name: 'GLS Munich Castle',
    location: 'Мюнхен, Германия',
    age: '14-17',
    date: '<a href="https://holidays.study.ua/trips/page/gls-munich-castle/" target="_blank">19.07 - 02.08 (2 нед.)</a>',
    cost: '€3100 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/french-riviera-summer/',
    flagWebp: 'img/programs-france.webp',
    flag: 'img/programs-france.jpg',
    flagAlt: 'Франция',
    webp: 'img/program-7.webp',
    jpg: 'img/program-7.jpg',
    alt: 'French Riviera summer',
    name: 'French Riviera summer',
    location: 'Ницца, Франция',
    age: '12-17',
    date: '<a href="https://holidays.study.ua/trips/page/french-riviera-summer/" target="_blank">04.07 - 18.07 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/french-riviera-summer/" target="_blank">18.07 - 01.08 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/french-riviera-summer/" target="_blank">01.08 - 15.08 (2 нед.)</a>',
    cost: '€2700 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/bhms-students/',
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-8.webp',
    jpg: 'img/program-8.jpg',
    alt: 'Business and Hotel Management School',
    name: 'Business and Hotel Management School',
    location: 'Люцерн, Швейцария',
    age: '15-23',
    date: '<a href="https://holidays.study.ua/trips/page/bhms-students/" target="_blank">04.07 - 18.07 (2 нед.)</a>',
    cost: '$4500 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/hospitality-business-experience-hotel-institute-montreux/',
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-9.webp',
    jpg: 'img/program-9.jpg',
    alt: 'Hospitality business experience',
    name: 'Hospitality business experience',
    location: 'Монтрё, Швейцария',
    age: '15-23',
    date: '<a href="https://holidays.study.ua/trips/page/hospitality-business-experience-hotel-institute-montreux/" target="_blank">21.07 - 03.08 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/hospitality-business-experience-hotel-institute-montreux/" target="_blank">04.08 - 17.08 (2 нед.)</a>',
    cost: '$4600 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/malta-junior-school/',
    flagWebp: 'img/programs-malta.webp',
    flag: 'img/programs-malta.jpg',
    flagAlt: 'Мальта',
    webp: 'img/program-10.webp',
    jpg: 'img/program-10.jpg',
    alt: 'Malta Junior School',
    name: 'Malta Junior School',
    location: 'Слима, Мальта',
    age: '13-17',
    date: '<a href="https://holidays.study.ua/trips/page/malta-junior-school/" target="_blank">04.07 - 17.07 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/malta-junior-school/" target="_blank">25.07 - 07.08 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/malta-junior-school/" target="_blank">08.08 - 21.08 (2 нед.)</a>',
    cost: '$2550 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/malta-kids-topaz-hotel/',
    flagWebp: 'img/programs-malta.webp',
    flag: 'img/programs-malta.jpg',
    flagAlt: 'Мальта',
    webp: 'img/program-11.webp',
    jpg: 'img/program-11.jpg',
    alt: 'Malta Kids School',
    name: 'Malta Kids School',
    location: 'Слима, Мальта',
    age: '8-12',
    date: '<a href="https://holidays.study.ua/trips/page/malta-kids-topaz-hotel/" target="_blank">18.07 - 31.07 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/malta-kids-topaz-hotel/" target="_blank">01.08 - 14.08 (2 нед.)</a>',
    cost: '€2500 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/canary-islands-barcelona/',
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Мальта',
    webp: 'img/program-12.webp',
    jpg: 'img/program-12.jpg',
    alt: 'Canary Islands + Barcelona',
    name: 'Canary Islands + Barcelona',
    location: 'Лас-Пальмас, Барселона',
    age: '14-17',
    date: '<a href="https://holidays.study.ua/trips/page/canary-islands-barcelona/" target="_blank">05.07 - 26.07 (3 нед.)</a>',
    cost: '€3800 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/barcelona-canary-islands/',
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Мальта',
    webp: 'img/program-13.webp',
    jpg: 'img/program-13.jpg',
    alt: 'Barcelona + Canary Islands',
    name: 'Barcelona + Canary Islands',
    location: 'Барселона, Лас-Пальмас',
    age: '14-17',
    date: '<a href="https://holidays.study.ua/trips/page/barcelona-canary-islands/" target="_blank">05.07 - 26.07 (3 нед.)</a>',
    cost: '€3900 (3 нед.)'
  }
];