var programsData = [
  // {
  //   full: false,
  //   href: 'http://summer.study.ua/trip/look/1109',
  //   flagWebp: 'img/programs-spain.webp',
  //   flag: 'img/programs-spain.jpg',
  //   flagAlt: 'Испания',
  //   webp: 'img/program-1.webp',
  //   jpg: 'img/program-1.jpg',
  //   alt: 'Malaga Summer camp',
  //   name: 'Malaga Summer camp',
  //   location: 'Испания, Малага',
  //   age: '11-17',
  //   date: '<a href="http://summer.study.ua/trip/look/1109" target="_blank">05.07 - 18.07 (2 нед.)</a>',
  //   cost: '€2750 (2 нед.)'
  // },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/1097',
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Испания',
    webp: 'img/program-2.webp',
    jpg: 'img/program-2.jpg',
    alt: 'Barcelona Summer camp',
    name: 'Barcelona Summer camp',
    location: 'Барселона',
    age: '14-18',
    date: '<a href="http://summer.study.ua/trip/look/1097" target="_blank">05.07 - 18.07 (2 нед.)</a>',
    cost: '€2800 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/1101',
    flagWebp: 'img/programs-spain.webp',
    flag: 'img/programs-spain.jpg',
    flagAlt: 'Испания',
    webp: 'img/program-3.webp',
    jpg: 'img/program-3.jpg',
    alt: 'EU International Business school',
    name: 'EU International Business school',
    location: 'Барселона',
    age: '16-18',
    date: '<a href="http://summer.study.ua/trip/look/1101" target="_blank">05.07 - 25.07 (3 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1103" target="_blank">02.08 - 22.08 (3 нед.)</a>',
    cost: '€4600 (3 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/57',
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-4.webp',
    jpg: 'img/program-4.jpg',
    alt: 'Alpadia Summer camp',
    name: 'Alpadia Summer camp',
    location: 'Энгельберг',
    age: '10-17',
    date: '<a href="http://summer.study.ua/trip/look/57" target="_blank">28.06 - 11.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1094" target="_blank">11.07 - 25.07 (2 нед.)</a>',
    cost: '$2800 (2 нед.) <br> $2900 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/1120',
    flagWebp: 'img/programs-malta.webp',
    flag: 'img/programs-malta.jpg',
    flagAlt: 'Мальта',
    webp: 'img/program-5.webp',
    jpg: 'img/program-5.jpg',
    alt: 'Malta IELS',
    name: 'Malta IELS',
    location: 'Слима',
    age: '13-17',
    date: '<a href="http://summer.study.ua/trip/look/1120" target="_blank">05.07 - 19.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1121" target="_blank">26.07 - 09.08 (2 нед.)</a>',
    cost: '$2550 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/1122',
    flagWebp: 'img/programs-germany.webp',
    flag: 'img/programs-germany.jpg',
    flagAlt: 'Германия',
    webp: 'img/program-6.webp',
    jpg: 'img/program-6.jpg',
    alt: 'GLS Munich Castle',
    name: 'GLS Munich Castle',
    location: 'Мюнхен',
    age: '14-17',
    date: '<a href="http://summer.study.ua/trip/look/1122" target="_blank">19.07 - 02.08 (2 нед.)</a>',
    cost: '€3100 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/62',
    flagWebp: 'img/programs-france.webp',
    flag: 'img/programs-france.jpg',
    flagAlt: 'Франция',
    webp: 'img/program-7.webp',
    jpg: 'img/program-7.jpg',
    alt: 'French Riviera summer',
    name: 'French Riviera summer',
    location: 'Ницца',
    age: '12-17',
    date: '<a href="http://summer.study.ua/trip/look/62" target="_blank">04.07 - 18.07 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/75" target="_blank">18.07 - 01.08 (2 нед.)</a> <br> <a href="http://summer.study.ua/trip/look/1077" target="_blank">01.08 - 15.08 (2 нед.)</a>',
    cost: '€3100 (2 нед.)'
  },
  {
    full: false,
    href: 'http://summer.study.ua/trip/look/61',
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-8.webp',
    jpg: 'img/program-8.jpg',
    alt: 'Business and Hotel Management School',
    name: 'Business and Hotel Management School',
    location: 'Люцерн',
    age: '15-23',
    date: '<a href="http://summer.study.ua/trip/look/61" target="_blank">04.07 - 18.07 (2 нед.)</a>',
    cost: '$4500 (2 нед.)'
  },
  {
    full: false,
    href: 'program/hospitality-business-experience.html',
    flagWebp: 'img/programs-switzerland.webp',
    flag: 'img/programs-switzerland.jpg',
    flagAlt: 'Швейцария',
    webp: 'img/program-9.webp',
    jpg: 'img/program-9.jpg',
    alt: 'Hospitality business experience',
    name: 'Hospitality business experience',
    location: 'Монтрё, Швейцария',
    age: '15-23',
    date: '<a href="program/hospitality-business-experience.html" target="_blank">21.07 - 03.08 (2 нед.)</a> <br> <a href="program/hospitality-business-experience.html" target="_blank">04.08 - 17.08 (2 нед.)</a>',
    cost: '$4600 (2 нед.)'
  },
  {
    full: false,
    href: 'program/malta-junior-school.html',
    flagWebp: 'img/programs-malta.webp',
    flag: 'img/programs-malta.jpg',
    flagAlt: 'Мальта',
    webp: 'img/program-10.webp',
    jpg: 'img/program-10.jpg',
    alt: 'Malta Junior School, Howard hotel',
    name: 'Malta Junior School, Howard hotel',
    location: 'Слима, Мальта',
    age: '13-17',
    date: '<a href="program/malta-junior-school.html" target="_blank">05.07 - 19.07 (2 нед.)</a> <br> <a href="program/malta-junior-school.html" target="_blank">26.07 - 09.08 (2 нед.)</a> <br> <a href="program/malta-junior-school.html" target="_blank">09.08 - 23.08 (2 нед.)</a>',
    cost: '$2550 (2 нед.)'
  }
];