var programsData = [
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/ec-english-london-students/',
    webp: 'img/program-1.webp',
    jpg: 'img/program-1.jpg',
    alt: 'EC English, London',
    name: 'EC English, London',
    location: 'Великобритания, Лондон',
    age: '18-23',
    date: '<a href="https://holidays.study.ua/trips/page/ec-english-london-students/" target="_blank">19.07 - 02.08</a>',
    cost: '$3650'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/iels-english-malta-students/',
    webp: 'img/program-2.webp',
    jpg: 'img/program-2.jpg',
    alt: 'Malta Summer',
    name: 'Malta Summer',
    location: 'Мальта, Сент-Джулианс',
    age: '18-23',
    date: '<a href="https://holidays.study.ua/trips/page/iels-english-malta-students/" target="_blank">08.08 - 21.08</a>',
    cost: '€2600'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/oxford-school-students/',
    webp: 'img/program-3.webp',
    jpg: 'img/program-3.jpg',
    alt: 'Oxford School of English',
    name: 'Oxford School of English',
    location: 'Великобритания, Оксфорд',
    age: '18-23',
    date: '<a href="https://holidays.study.ua/trips/page/oxford-school-students/" target="_blank">01.08 - 22.08</a>',
    cost: '$3800'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/ilac-students/',
    webp: 'img/program-4.webp',
    jpg: 'img/program-4.jpg',
    alt: 'ILAC',
    name: 'ILAC',
    location: 'Канада, Торонто',
    age: '18-23',
    date: '<a href="https://holidays.study.ua/trips/page/ilac-students/" target="_blank">25.07 - 22.08</a>',
    cost: '$5200'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/ec-english-canada-students/',
    webp: 'img/program-5.webp',
    jpg: 'img/program-5.jpg',
    alt: 'EC English Toronto + Vancouver',
    name: 'EC English Toronto + Vancouver',
    location: 'Канада, Торонто, Ванкувер',
    age: '18-23',
    date: '<a href="https://holidays.study.ua/trips/page/ec-english-canada-students/" target="_blank">18.07 - 15.08</a>',
    cost: '$5400'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/niagara-college-students/',
    webp: 'img/program-6.webp',
    jpg: 'img/program-6.jpg',
    alt: 'Niagara College',
    name: 'Niagara College',
    location: 'Канада, Велланд',
    age: '16-23',
    date: '<a href="https://holidays.study.ua/trips/page/niagara-college-students/" target="_blank">25.07 - 22.08 </a>',
    cost: '$4700'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/bhms-students/',
    webp: 'img/program-7.webp',
    jpg: 'img/program-7.jpg',
    alt: 'Hotel and Restaurant business experience',
    name: 'Hotel and Restaurant business experience',
    location: 'Швейцария, Люцерн',
    age: '15-23',
    date: '<a href="https://holidays.study.ua/trips/page/bhms-students/" target="_blank">04.07 - 18.07</a>',
    cost: '$4500'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/hospitality-business-experience-hotel-institute-montreux/',
    webp: 'img/program-8.webp',
    jpg: 'img/program-8.jpg',
    alt: 'Hospitality business experience',
    name: 'Hospitality business experience',
    location: 'Монтрё, Швейцария',
    age: '15-23',
    date: '<a href="https://holidays.study.ua/trips/page/hospitality-business-experience-hotel-institute-montreux/" target="_blank">21.07 - 03.08 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/hospitality-business-experience-hotel-institute-montreux/" target="_blank">04.08 - 17.08 (2 нед.)</a>',
    cost: '$4600 (2 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/stay-campus-camden/',
    webp: 'img/program-9.webp',
    jpg: 'img/program-9.jpg',
    alt: 'Stay Campus London',
    name: 'Stay Campus London',
    location: 'Лондон, Великобритания',
    age: '18-23',
    date: '<a href="https://holidays.study.ua/trips/page/stay-campus-camden/" target="_blank">02.08 - 16.08 (2 нед.)</a> <br> <a href="https://holidays.study.ua/trips/page/stay-campus-camden/" target="_blank">02.08 - 23.08 (3 нед.)</a>',
    cost: '$3650 (2 нед.) <br> $4550 (3 нед.)'
  },
  {
    full: false,
    href: 'https://holidays.study.ua/trips/page/business-simulation-program/',
    webp: 'img/program-10.webp',
    jpg: 'img/program-10.jpg',
    alt: 'Business Simulation Program',
    name: 'Business Simulation Program',
    location: 'Борнмут, Великобритания',
    age: '16-25',
    date: '<a href="https://holidays.study.ua/trips/page/business-simulation-program/" target="_blank">25.07 - 22.08 (4 нед.)</a>',
    cost: '$4300 (5 нед.)'
  }
];